###############################################################
###############################################################
###############################################################
perf=data.frame(RMBC=rep(NaN,5),TCLUSTOracle=rep(NaN,5),MCLUST=rep(NaN,5),Otrimle=rep(NaN,5))
thetaNew.mu=resultRMBC$mu;
thetaNew.sigma=resultRMBC$Sigma
thetaNew.alpha=resultRMBC$alpha
medRMBC=performance_measures(Y,indicesDGP,thetaNew.alpha,
                             thetaNew.mu,thetaNew.sigma,actualAlpha=thetaNewClasRef.alpha,
                             actualSigma=thetaNewClasRef.sigma,actualMu=thetaNewClasRef.mu,nkl=1000000)
MCRs=medRMBC$mcrSinCero
MCR0s=medRMBC$mcr
Specificitys=medRMBC$specificity
Sensitivitys=medRMBC$sensitivity
KLs=medRMBC$kl[1]
todo=c(MCRs, MCR0s,Specificitys,Sensitivitys,KLs);
perf$RMBC<-todo

#medTCLUST=performance_measures(Y,indicesDGP,thetaNewTclust.alpha,
#                               thetaNewTclust.mu,thetaNewTclust.sigma,actualAlpha=thetaNewClasRef.alpha,
#                               actualSigma=thetaNewClasRef.sigma,actualMu=thetaNewClasRef.mu,nkl=10000)
#Specificitys=medTCLUST$specificity
#Sensitivitys=medTCLUST$sensitivity
#MCRs=medTCLUST$mcrSinCero
#MCR0s=medTCLUST$mcr
#KLs=medTCLUST$kl[1]
#todo=c(MCRs, MCR0s,Specificitys,Sensitivitys,KLs);
#perf$TCLUST<-todo

medTCLUSTOracle=performance_measures(Y,indicesDGP,thetaNewTclustOracle.alpha,
                                     thetaNewTclustOracle.mu,thetaNewTclustOracle.sigma,actualAlpha=thetaNewClasRef.alpha,
                                     actualSigma=thetaNewClasRef.sigma,actualMu=thetaNewClasRef.mu,nkl=10000)

Specificitys=  medTCLUSTOracle$specificity
Sensitivitys=  medTCLUSTOracle$sensitivity
MCRs=medTCLUSTOracle$mcrSinCero
MCR0s=medTCLUSTOracle$mcr
KLs=medTCLUSTOracle$kl[1]
todo=c(MCRs, MCR0s,Specificitys,Sensitivitys,KLs);
perf$TCLUSTOracle<-todo


medMCLUST=performance_measures(Y,indicesDGP,thetaNewClas.alpha,
                               thetaNewClas.mu,thetaNewClas.sigma,actualAlpha=thetaNewClasRef.alpha,
                               actualSigma=thetaNewClasRef.sigma,actualMu=thetaNewClasRef.mu,nkl=10000)

Specificitys=medMCLUST$specificity
Sensitivitys=medMCLUST$sensitivity
MCRs=medMCLUST$mcrSinCero
MCR0s=medMCLUST$mcr
KLs=medMCLUST$kl[1]
todo=c(MCRs, MCR0s,Specificitys,Sensitivitys,KLs);
perf$MCLUST<-todo

medOtrimle=performance_measures(Y,indicesDGP,thetaNewOtrimle.alpha,
                                thetaNewOtrimle.mu,thetaNewOtrimle.sigma,actualAlpha=thetaNewClasRef.alpha,
                                actualSigma=thetaNewClasRef.sigma,actualMu=thetaNewClasRef.mu,nkl=10000)
Specificitys=medOtrimle$specificity
Sensitivitys=medOtrimle$sensitivity
MCRs=medOtrimle$mcrSinCero
MCR0s=medOtrimle$mcr
KLs=medOtrimle$kl[1]
todo=c(MCRs, MCR0s,Specificitys,Sensitivitys,KLs);
perf$Otrimle<-todo

#################################################
# the table is generated by library xtable ######
#################################################

library(xtable)
u=colnames(perf)
u[2]="TCLUST"
#u[3]="TCLUST_{0.20}"
colnames(perf)<-u;
rownames(perf)<-c("MCR", "MCR_0", "Specificity","Sensitivity","K-L")
captionTable="Performance of the compared clustering procedures when applied to the phy-
toplankton data. The subscripts on TCLUST are the values of the trimming parameter alpha. The choice 0.20 corresponds to the actual known fraction of outliers in the given data
(ORACLE). textbf{MCR}:Misclassification Rate. textbf{MCR_0}: Misclassification Rate, 
taking into account K+1 clusters, where Outliers-clusters 
are considered with zero-index.  textbf{KL} Kullback-Leibler divergence."
write.csv(perf,"Table3.csv",row.names= T)

